version: 0.2

phases:
  install:
    commands:
      - echo "Instalando Terraform"
  pre_build:
    commands:
      - terraform init
      - terraform validate
  build:
    commands:
      - terraform apply -var-file="terraform.tfvars" -auto-approve

artifacts:
  files:
    - '**/*'